config/routes.rb
Rails.application.routes.draw do

  match 'import/btc', via: [:get, :post]

  root to: 'home#index'

  get 'wallet' => 'home#wallet', as: :wallet
  put 'wallet/status' => 'home#status', as: :wallet_status
  get 'wallet/history' => 'home#history', as: :wallet_history
  get 'wallet/:address/txes' => 'home#txes', as: :wallet_txes
  match 'purchase' => 'home#purchase', as: :purchase, via: [:get, :put, :post]

  get 'api/btc/confirm'
  post 'api/btc/fresh'

  resources :charges

  devise_for :accounts, controllers: {
    registrations: 'account/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_account!, only: :index

  def index
    # @charge = Charge.new
  end

  def wallet
    @verify_btcs = current_account.btcs.where(status: [0, 1])
  end

  def history
    params[:type] ||= 'btc'
    @wallets = case params[:type]
               when 'ltc'
                 current_account.ltcs
               when 'eth'
                 current_account.eths
               else
                 current_account.btcs
               end
    @wallets = current_account.btcs.order(id: :desc)
    @wallets = @wallets.page params[:page]
  end

  def purchase
    if request.xhr?
      if params[:token] && params[:type] == 'get_purchase'
        @btc  = params[:token].to_d / BtcAddress::TOKEN_UNIT
        @code = current_account.purchase_btc_wallet_code
      elsif params[:type] == 'purchase'
        @result = current_account.purchase_btc(params[:code], params[:amount])
      end
    end
  end

  def status
    @transaction = Transaction.find params[:id]
    if @transaction.confirm? && params[:t] == 'confirm'
      @transaction.finish!
    end
  end

  def txes
    @txes = Tx.where(address: params[:address]).page(params[:page]).per 10
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_txes.html.erb
<table class="table">
  <thead>
    <tr>
      <th>
        <span>Number</span>
      </th>
      <th>
        <span>txid</span>
      </th>
      <th>
        <span>BTC</span>
      </th>
      <th>
        <span>Token</span>
      </th>
      <th>
        <span>Confirmations</span>
      </th>
    </tr>
  </thead>
  <tbody>
    <%txes.each_with_index do |c, i|%>
      <tr class="<%= c.finish? ? 'success' : (c.unfinish? ? 'error' : 'info') %>">
        <td>
          <%= i + 1%>
        </td>
        <td>
          <%= c.txid %>
        </td>
        <td>
          <%= c.amount %>
        </td>
        <td>
          <%= c.paidToken %>
        </td>
        <td>
          <%= c.confirmations %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

<%= paginate txes, remote: true %>

app/views/home/history.html.erb
<div class="container">
  <br>
  <ul class="nav nav-pills">
    <li role="presentation"><a href="/">Home</a></li>
    <li role="presentation"><a href="/wallet">My Wallet</a></li>
    <li role="presentation">
      <%= link_to 'Logout', destroy_account_session_path, method: :delete %>
    </li>
  </ul>

  <div class="row-fluid">
    <div class="span12">
      <h3>
        Purchase history
      </h3>
      <table class="table">
        <thead>
          <tr>
            <th>
              <span>Number</span>
            </th>
            <th>
              <span>Address</span>
            </th>
            <th>
              <span>Token</span>
            </th>
            <th>
              <span>BTC</span>
            </th>
            <th>
              <span>TokenAmount</span>
            </th>
            <th>
              <span>payAmount</span>
            </th>
            <th>
              <span>Purchase</span>
            </th>
            <th>
              <span>Status</span>
            </th>
          </tr>
        </thead>
        <tbody>
          <%@wallets.each_with_index do |c, i|%>
            <tr class="<%= c.finish? ? 'success' : (c.fails? ? 'error' : 'info') %>">
              <td>
                <%= i + 1%>
              </td>
              <td>
                <a href="https://blockexplorer.com/address/<%= c.Address%>"><%= c.Address%></a>
              </td>
              <td>
                <%= c.Token %>
              </td>
              <td>
                <%= c.Btc %>
              </td>
              <td>
                <%= c.TokenAmount %>
                &nbsp;
                <%= link_to "details", wallet_txes_path(address: c.Address), remote: true %>
              </td>
              <td>
                <%= c.payAmount %>
              </td>
              <td>
                <%= c.created_at.strftime("%d/%m/%Y %H:%M:%S")%>
              </td>
              <td id="status-<%= c.ID %>">
                <%= link_to_if c.confirm?, c.status.titleize, wallet_status_path(id: c.ID, t: :confirm), method: :put, data: {confirm: 'confirm the transaction is finish?'}, remote: true %>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
      <%= paginate @wallets %>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-wallet-txes" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">
          Wallet(<span id="wallet-address"></span>) Txes
        </h4>
      </div>
      <div class="modal-body" id="wallet-txes-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/purchase.html.erb
<div class="container purchase-page">
    <br>
    <ul class="nav nav-pills">
      <li role="presentation"><a href="/">Home</a></li>
      <li role="presentation" class="active"><a href="/wallet">My Wallet</a></li>
      <li role="presentation">
        <%= link_to 'Logout', destroy_account_session_path, method: :delete %>
      </li>
    </ul>
  <div class="row clearfix">
    <div class="col-md-12 column">
      <h1>
        Purchase token
      </h1>
    </div>
    <div class="modal fade" id="modal-purchase-token" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="myModalLabel">
              Purchase by BTC
            </h4>
          </div>
          <div class="modal-body">
            <span class="purchase-token"></span> token need <span class="purchase-btc"></span>BTC
            please send <span class="purchase-btc"></span>BTC todo this address : <span class="purchase-btc-code"></span>
            <div class="purchase-qrcode">
            </div>
          </div>
          <div class="modal-footer">
            <%= form_with remote: true do |form|%>
              <%= form.hidden_field :type, value: 'purchase'%>
              <%= form.hidden_field :amount, id: 'purchase-input-amount' %>
              <%= form.hidden_field :code, id: 'purchase-input-code' %>
              <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>
              <button type="submit" class="btn btn-primary">purchase</button>
            <%end%>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="modal-purchase-success" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="myModalLabel">
              Purchase Success
            </h4>
          </div>
          <%# <div class="modal-body"></div> %>
          <div class="modal-footer">
            <%= form_with remote: true do |form|%>
              <%= form.hidden_field :type, value: 'purchase'%>
              <%= form.hidden_field :amount %>
              <%= form.hidden_field :code %>
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <a type="submit" role="button" href="/wallet" class="btn btn-primary">Go to my wallet</a>
            <%end%>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="modal-purchase-error" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="myModalLabel">
              Purchase Error
            </h4>
          </div>
          <div class="modal-body">Wallet address invalid, please try again after refresh</div>
          <div class="modal-footer">
            <%= form_with remote: true do |form|%>
              <%= form.hidden_field :type, value: 'purchase'%>
              <%= form.hidden_field :amount %>
              <%= form.hidden_field :code %>
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <a type="submit" role="button" href="/wallet" class="btn btn-primary">Go to my wallet</a>
            <%end%>
          </div>
        </div>
      </div>
    </div>

    <div class="row clearfix">
      <% [1000, 2000, 3000].each do |token|%>
        <div class="col-md-4 column">
          <%= link_to "#{token} Token", purchase_path(type: 'get_purchase', token: token), class: 'btn', role: 'button', remote: true%>
          <%# <a id="modal-476150" href="#modal-container-476150" role="button" class="btn" data-toggle="modal">1000 Token</a> %>
        </div>
      <%end%>
    </div>
    <div class="row clearfix">
      <% [4000, 5000, 6000].each do |token|%>
        <div class="col-md-4 column">
          <%= link_to "#{token} Token", purchase_path(type: 'get_purchase', token: token), class: 'btn', role: 'button', remote: true%>
          <%# <a id="modal-476150" href="#modal-container-476150" role="button" class="btn" data-toggle="modal">1000 Token</a> %>
        </div>
      <%end%>
    </div>
  </div>

app/views/home/purchase.js.erb
<%if params[:type] == 'get_purchase' %>
  var code = '<%= @code %>'
  var btc  = <%= @btc %>
  $(".purchase-token").html('<%= params[:token]%>')

  $(".purchase-btc").html(btc)
$(".purchase-qrcode").html('<%= j image_tag "https://bitaps.com/api/qrcode/png/#{ERB::Util.url_encode("bitcoin:#{@code}?amount=#{@btc}&label=Luke-Jr")}" %>')

  $(".purchase-btc-code").html(code)

  $('#purchase-input-amount').val(btc)
  $('#purchase-input-code').val(code)

  $("#modal-purchase-token").modal('show')

<%elsif params[:type] == 'purchase' %>
  $("#modal-purchase-token").modal('hide')

  var result = <%== @result.to_json %>
  if (result.status === 'OK') {
    $('#modal-purchase-success').modal({show: true})
  } else {
    $('#modal-purchase-error').modal({show: true})
  }
<%end%>

app/views/home/status.js.erb
$("#status-<%= @transaction.ID %>").html("<%= @transaction.status %>")
$("#status-<%= @transaction.ID %>").closest('tr').removeClass().addClass("success")

app/views/home/txes.js.erb
$('#wallet-address').html('<%= params[:address] %>')
$('#wallet-txes-body').html('<%= j render 'txes', txes: @txes %>')

$('#modal-wallet-txes').modal('show')

app/views/home/wallet.html.erb
<div class="container">
  <br>
  <ul class="nav nav-pills">
    <li role="presentation"><a href="/">Home</a></li>
    <li role="presentation" class="active"><a href="#">My Wallet</a></li>
    <li role="presentation">
      <%= link_to 'Logout', destroy_account_session_path, method: :delete %>
    </li>
  </ul>
  <div class="row-fluid">
    <div class="span12">
      <%= content_tag :h1, id: 'wallet-title', data: {btcs: @verify_btcs.map{|b| {address: b.Address, confirm_count: b.confirm_txes_count, count: b.txes_count}}} do %>
        My wallet
      <% end %>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span4">
      <p>
      <strong>My token : <%= current_account.total_btc_token %></strong>
      </p>
    </div>
    <div class="span4">
      <p>
      <strong><span>Unconfirmations ： <%= current_account.unconfirmation_btc_token %></span></strong>
      </p>
    </div>
    <div class="span4">
      <%= link_to "Purchase Histories",wallet_history_path, class: 'btn btn-info' %> &nbsp;&nbsp;&nbsp;&nbsp;
      <% if Transaction.enable_token > 0 %>
        <%= link_to "Purchase",purchase_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>